# Generated by Django 4.2.3 on 2023-07-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_published',
            new_name='published',
        ),
    ]
