# Generated by Django 4.2.3 on 2023-08-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='active_version',
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание версии'),
        ),
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная версия'),
        ),
    ]
